<?php

/**
 * Implements hook_theme().
 */
function monitoring_drupal_theme(): array {
  return [
    'webprofiler_profiler_toolbar' => [
      'template' => 'profiler_toolbar',
      'variables' => [
        'time' => NULL,
        'memory' => '',
        'queries' => NULL,
        'queries_list' => [],
        'queries_time' => NULL,
        'cache_hits' => NULL,
        'cache_misses' => NULL,
        'cache_ratio' => NULL,
        'cache_sets' => NULL,
        'caches_errors' => NULL
      ]
    ]
  ];
}