<?php

/**
 * Implements hook_theme().
 */
function monitoring_drupal_theme(): array {
  return [
    'webprofiler_profiler_toolbar' => [
      'template' => 'profiler_toolbar',
      'variables' => [
        'excluded_ajax_paths' => '^\/.*\/profiler\/[a-z0-9]*',
        'token' => '',
        'request' => NULL,
        'csp_script_nonce' => '',
        'csp_style_nonce' => ''
      ]
    ]
  ];
}