# Schema for the configuration files of the monitoring_drupal module.
monitoring_drupal.settings:
  type: config_object
  label: 'monitoring_drupal settings'
  mapping:
    example:
      type: string
      label: 'Example'
