monitoring_drupal.settings:
  type: config_object
  label: 'Monitoring Drupal settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable profiler'
    show_toolbar:
      type: boolean
      label: 'Show toolbar'
    allowed_roles:
      type: sequence
      label: 'Allowed roles'
      sequence:
        type: string
        label: 'Role'